spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ai-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aidb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Admin@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8082}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}

google:
  api:
    key: ${GOOGLE_API_KEY:AIzaSyA_Gjapt-dzFaLIbLpBqQBUcEX6aku_4QU}