spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: gym-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gymdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Admin@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}

vnp:
  vnp_TmnCode: ${VNP_TMN_CODE:TESTCODE}
  vnp_HashSecret: ${VNP_HASH_SECRET:TESTSECRET}
  vnp_Url: ${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  vnp_ReturnUrl: ${VNP_RETURN_URL:http://localhost:8080/api/payment/return}