spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: user-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Admin@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:trunglu2602@gmail.com}
    password: ${MAIL_PASSWORD:zlte yfay elus gxxc}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
          connectiontimeout: ${MAIL_CONNECTION_TIMEOUT:5000}
          timeout: ${MAIL_TIMEOUT:3000}
          writetimeout: ${MAIL_WRITE_TIMEOUT:5000}

server:
  port: ${SERVER_PORT:8081}

gym:
  service:
    url: ${GYM_SERVICE_URL:http://localhost:8080}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dxgc9wwrd}
  api-key: ${CLOUDINARY_API_KEY:167655672385223}
  api-secret: ${CLOUDINARY_API_SECRET:AIzaSyA_Gjapt-dzFaLIbLpBqQBUcEX6aku_4QUapp}